stages:
  - build-and-test
  - unit-tests

build-job:
  stage: build-and-test
  image: openjdk:11-jdk-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew build

unit-testing-job:
  stage: unit-tests
  script:
    - chmod +x ./gradlew
    - export JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk-amd64"
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
