stages:
  - build-and-test
  - unit-tests

build-job:
  stage: build-and-test
  image: openjdk:17.0.2-jdk-oracle
  script:
    - chmod +x ./gradlew
    - ./gradlew build

unit-testing-job:
  stage: unit-tests
  image: openjdk:17.0.2-jdk-oracle
  script:
    - chmod +x ./gradlew
    - export JAVA_HOME="/usr/java/openjdk-17"
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
