stages:
  - build-and-test
  - unit-tests

build-job:
  stage: build-and-test
  image: kainoscom/jdk-17-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew build

unit-testing-job:
  stage: unit-tests
  script:
    - chmod +x ./gradlew
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
